package com.apm29.beanmodule.beans.ding

import com.google.gson.annotations.SerializedName

data class ProjectBean(val loginTypeTip: String = "",
                       val addTime: Long = 0,
                       val investDirectionTitle: String = "",
                       val modifyUserId: Int = 0,
                       val type: Int = 0,
                       val score: Int = 0,
                       val investDirectionDescr: String = "",
                       val freeze: Int = 0,
                       val modifyTime: Long = 0,
                       val subTitle: String = "",
                       val id: Int = 0,
                       val newPreferential: Int = 0,
                       val localTop: Int = 0,
                       val period: Int = 0,
                       val addUserId: Int = 0,
                       @SerializedName("isH5")
                      val isH5: Int = 0,
                       val stoneNo: String = "",
                       val userInterest: Double = 0.0,
                       val globalTop: Int = 0,
                       val projectDuration: Int = 0,
                       val remindText: String = "",
                       val moneyMax: Int = 0,
                       @SerializedName("countInterestType3")
                      val countInterestType3: Int = 0,
                       val giveoutInterest: Int = 0,
                       val corporationEarnings: Int = 0,
                       val lastmonths: Int = 0,
                       val investDirectionImage: String = "",
                       val status: Int = 0,
                       @SerializedName("paySucByH5")
                      val paySucByH5: Int = 0,
                       val userRaiseInterest: Int = 0,
                       val moneyMin: Int = 0,
                       val repaymentSourceImage: String = "",
                       val loginType: Int = 0,
                       val contractNo: String = "",
                       val collectamount: Int = 0,
                       val termType: Int = 0,
                       val countInterestType: Int = 0,
                       val remark: String = "",
                       val repaymentSourceDescr: String = "",
                       val title: String = "",
                       val percent: Int = 0,
                       val duration: Int = 0,
                       val canSubscribe: Int = 0,
                       val repaymentDay: Int = 0,
                       val repaymentSource: String = "",
                       val repaymentType: Int = 0,
                       val investDirection: String = "",
                       val buyTimes: Int = 0,
                       val financing: String = "",
                       val nickname: String = "",
                       val startTime: Long = 0,
                       val views: Int = 0,
                       val contractInterest: Double = 0.0,
                       val amount: Int = 0,
                       val buyBase: Int = 0,
                       val isDelete: Int = 0,
                       val durationDay: Int = 0,
                       val repaymentSourceTitle: String = "",
                       val currentSystemTime: Long = 0,
                       val newTop: Int = 0,
                       val isCountdown: Int = 0,
                       val vipUserIds: String = "",
                       val vipUserId: Int = 0,
                       val stage: Int = 0,
                       val able: Int = 0,
                       val idcard: String = "",
                       val endTime: Long = 0,
                       val activityType: Int = 0)